# Generated by Django 2.2.19 on 2021-04-01 15:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentmodel',
            name='time_execution',
        ),
        migrations.RemoveField(
            model_name='assignmentmodel',
            name='value',
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
