# Generated by Django 2.2.19 on 2021-04-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20210401_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='type_input',
            field=models.IntegerField(choices=[(10, 'Json'), (20, 'String')], default=0),
            preserve_default=False,
        ),
    ]
